# ~/.config/starship.toml

# Use custom format
format = '''
[┌─\[](bold gray) $directory$rust$python$package$git_branch[\]](bold gray)
[└](bold gray)[❯](bold green) '''

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

# A continuation prompt that displays two filled-in arrows
continuation_prompt = '''[▶](bold gray) '''

# Set 'foo' as custom color palette
palette = 'foo'

# Define custom colors
[palettes.foo]
# Overwrite existing color
blue = '21'
# Define new color
mustard = '#af8700'
gray = '#45475a'
