icons_format = "{icon}"

[theme]
theme = "ctp-mocha"
[theme.overrides]
idle_fg = "#9399b2"
idle_bg = ""
separator_fg = "#45475a"
separator = " "

[icons]
icons = "awesome4"

[[block]]
block = "backlight"

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "battery"
[block.theme_overrides]
idle_bg = "#11111b"
info_bg = "#11111b"
good_bg = "#11111b"
warning_bg = "#11111b"
critical_bg = "#11111b"
idle_fg = "#b4befe"
info_fg = "#b4befe"
good_fg = "#b4befe"
warning_fg = "#b4befe"
critical_fg = "#b4befe"




[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
[block.theme_overrides]
idle_fg = "#11111b"
idle_bg = "#b4befe"
